### ISSUE TITLE
Add "support" for ggblend

### ISSUE THREAD

**Issue by CGMossa** [davidhodge931/ggblanket#116]
I'm very much impressed by this package. The only thing I thought off when reading the readme, is that
the `alpha` channel is manipulated, and it could instead benefit from [ggblend](https://mjskay.github.io/ggblend/index.html).

I don't know what support entails; If it is just plug both in, or if `ggblend` should be used in this package by default;
But the issue could be discussion point for this.

**Comment by davidhodge931** [comment]
Thanks @CGMossa 

I'm trying to keep the package with minimal and solid dependencies, so that it is more future-proof.

If you would like to use {ggblanket} with {ggblend},  I would recommend using `ggblanket::ggblank()` 

```
library(ggplot2)
library(ggblend)
library(ggblanket)

set.seed(1234)

df_a = data.frame(x = rnorm(500, 0), y = rnorm(500, 1), set = "a")
df_b = data.frame(x = rnorm(500, 1), y = rnorm(500, 2), set = "b")

df_ab = rbind(df_a, df_b) |>
  transform(order = "draw a then b")

df_ab %>%
  gg_blank(x = x,
           y = y,
           col = set,
           pal = brewer.pal("Set2", n = 8),
           title = "Scatterplot with blend('darken'): draw order does not matter") +
  geom_point(size = 3) |> blend("multiply", alpha = 0.65) 
```

<img width="414" alt="image" src="https://user-images.githubusercontent.com/55065152/168448191-13f46aad-d873-41cb-bd64-649f6000177a.png">

**Comment by davidhodge931** [comment]
Give the package a star if you like it :)
