### ISSUE TITLE
tests: add visual tests into the package

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/ggblanket#647]
How do I add some tests into this package?

At present, I use the devtools::check plus visually look at the vignette and articles to make sure everything is working.

Is there are better way to do this?

**Comment by olivroy** [comment]
I can sketch it for you!

* you want to test if errors occur on undesirable input
* you may want to snapshot the look of certain plots with vdiffr and `expect_doppelganger()` https://vdiffr.r-lib.org/reference/expect_doppelganger.html
* test for the types of geoms etc. 
* test if edge cases error gracefully 

see https://testthat.r-lib.org or https://r-pkgs.org/testing-basics.html

Visually looking at vignettes is good at the beginning but when the packages matures, you will not be actively maintaining it, and tests will be your best guadrdian because potential failures will force you to look it over ;)

**Comment by davidhodge931** [comment]
Thanks @olivroy I've just added some `expect_equal` tests in for my `replace_seq` function.

Are you able to provide an example visual test using `expect_doppleganger` to demo to me how this works?

So just that a simple graph looks right like below?? 

``` r
library(palmerpenguins)
library(ggblanket)

penguins |>
  gg_point(
    x = flipper_length_mm,
    y = body_mass_g,
  )
#> Warning in gg_blanket(data = data, geom = "point", stat = stat, position = position, : Ignoring unknown parameters: `contour`
#> Ignoring unknown parameters: `contour`
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/VGn5CHg.png)

<sup>Created on 2024-01-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
https://www.tidyverse.org/blog/2021/06/vdiffr-1-0-0/
